x-postgres-environment: &postgres-environment
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432

x-airflow-environment: &airflow-environment
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/airflow
  AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  PROXY_USERNAME: ${PROXY_USERNAME}
  PASSWORD: ${PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  AIRFLOW__CORE__EXECUTION_API_SERVER_URL: http://airflow-api:8080/execution/
  AIRFLOW__API_AUTH__JWT_SECRET: ${AIRFLOW__API_AUTH__JWT_SECRET}

services:
  postgres:
    image: postgres:14.24-alpine3.23
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    secrets:
      - db_password
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer:latest
    container_name: adminer_ui
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  api:
    image: offers-api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: offers_api
    environment:
      <<: *postgres-environment
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  airflow-migrate:
    image: airflow-workflows-manager:latest
    build:
      context: ./pipeline
      dockerfile: Dockerfile
    container_name: airflow_migrate
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/airflow
    depends_on:
      postgres:
        condition: service_healthy
    command: ["db", "migrate"]
    networks:
      - app-network

  airflow-api:
    image: airflow-workflows-manager:latest
    build:
      context: ./pipeline
      dockerfile: Dockerfile
    container_name: airflow-api
    environment:
      <<: *airflow-environment
    depends_on:
      airflow-migrate:
        condition: service_completed_successfully
    ports:
      - "8081:8080"
    command: ["api-server"]
    networks:
      - app-network
    volumes:
      - ./proxy-list.txt:/opt/airflow/data/proxy-list.txt:ro
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/api/v2/monitor/health', timeout=5)"]
      interval: 10s
      timeout: 6s
      retries: 10
      start_period: 30s
    
  airflow-dag-processor:
    image: airflow-workflows-manager:latest
    build:
      context: ./pipeline
      dockerfile: Dockerfile
    container_name: airflow_dag_processor
    environment:
      <<: *airflow-environment
    depends_on:
      airflow-migrate:
        condition: service_completed_successfully
    command: ["dag-processor"]
    networks:
      - app-network
    volumes:
      - ./proxy-list.txt:/opt/airflow/data/proxy-list.txt:ro

  airflow-scheduler:
    image: airflow-workflows-manager:latest
    build:
      context: ./pipeline
      dockerfile: Dockerfile
    container_name: airflow_scheduler
    environment:
      <<: *airflow-environment
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    depends_on:
      airflow-migrate:
        condition: service_completed_successfully
      airflow-api:
        condition: service_healthy
    command: ["scheduler"]
    networks:
      - app-network
    volumes:
      - ./proxy-list.txt:/opt/airflow/data/proxy-list.txt:ro

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge

secrets:
  db_password:
    file: ./db_password.txt