FROM python:3.14-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN playwright install --with-deps chromium 
COPY . ./scraper/
CMD ["python", "-m", "scraper.run"]